### PR TITLE
Transfer cookies from backend

### PR DESCRIPTION
**Pull request by levonet**
It's needed for transfer session cookies from the backend to a client and back it again (like haproxy).

### CODE REVIEW

**Comment by JonathanHuot** [comment]
It looks a very great addition! let us have review it.

**Comment by steamboatid** [comment]
I havent tested it yet, but I managed to compiled it with nginx 1.21.6

image

**Comment by ftntming** [comment]
Any updates?

**Comment by JonathanHuot** [comment]
Thanks for the PR!

**Pull request merged**
